--DOCUMENTAÇÃO NEW ( CRIAÇÃO DE TABELAS ) 

DROP TABLE nucleoinfo.SOLICITACAO;

CREATE TABLE nucleoinfo.SOLICITACAO(
CD_SOLICITACAO         INT NOT NULL, 
CD_OS_MV               INT NOT NULL, ---FK TABELA SOLICITACAO_OS MV
CD_RESPONSAVEL         INT NULL,
TP_PRIORIDADE          VARCHAR(1), 
TP_TIPO                VARCHAR(1), --(S) --SOLICITACAO DE LEVANTAMENTO DE DADOS
ESTIMATIVA_ENTREGA     DATE,
RAMAL_SOLICITANTE      VARCHAR2(20),
EMAIL_SOLICITANTE      VARCHAR2(50),
CD_USUARIO_CADASTRO    VARCHAR(20),  ---FK TABELA USUARIOS MV
HR_CADASTRO            TIMESTAMP,
CD_USUARIO_ULT_ALT     VARCHAR(20),  ---FK TABELA USUARIOS MV
HR_ULT_ALT             TIMESTAMP,

--PRIMARY_KEY
CONSTRAINT PK_CD_SOLICITACAO PRIMARY KEY (CD_SOLICITACAO),

--CHECK
CONSTRAINT CK_TP_TIPO
CHECK (TP_TIPO IN ('S')),

--CHECK
CONSTRAINT CK_TP_PRIORIDADE
CHECK (TP_PRIORIDADE IN ('M'))

);

----------------------
--SEQ_CD_SOLICITACAO--
----------------------


DROP SEQUENCE nucleoinfo.SEQ_CD_SOLICITACAO;

CREATE SEQUENCE nucleoinfo.SEQ_CD_SOLICITACAO
START WITH 1    
INCREMENT BY 1
NOCACHE
NOCYCLE;



DROP TABLE nucleoinfo.ANEXOS;

CREATE TABLE nucleoinfo.ANEXOS(
CD_ANEXOS                  INT NOT NULL,
CD_OS_MV                   INT NOT NULL,
DOCUMENTO                  BLOB,
EXTENSAO                   VARCHAR(5),
CD_USUARIO_CADASTRO        VARCHAR(20),
HR_CADASTRO                TIMESTAMP,
CD_USUARIO_ULT_ALT         VARCHAR(20),
HR_ULT_ALT                 TIMESTAMP


);

----------------------
--SEQ_CD_ANEXOS-----
----------------------

DROP SEQUENCE nucleoinfo.SEQ_CD_ANEXOS;

CREATE SEQUENCE nucleoinfo.SEQ_CD_ANEXOS
START WITH 1    
INCREMENT BY 1
NOCACHE
NOCYCLE;




