
SELECT 
   SUBSTR(res.PERIODO, 4,10) AS PERIODO,
   res.CD_PRESTADOR_REPASSE,
   res.CD_PRESTADOR,
   res.NM_PRESTADOR,
   res.DS_ESPECIALID,
   res.EMPRESA,
   SUM(QTD_CONSULTAS_ATD) AS TOTAL_ATD_MES,
   SUM(QTD_CONSULTAS_RETORNO) AS TOTAL_ATD_MES_RETORNO,
   SUM(res.QTD_CONSULTAS_TOTAL) AS TOTAL_ATD_MES_TOTAL
FROM (SELECT
      TO_DATE(TO_CHAR(atd.DT_ATENDIMENTO,'DD/MM/YYYY'),'DD/MM/YYYY') AS PERIODO,
      prest.CD_PRESTADOR_REPASSE,
      prest.CD_PRESTADOR,
      prest.NM_PRESTADOR,
      espec.DS_ESPECIALID,
      atd.CD_ORI_ATE,
      CASE WHEN prest.DS_OBS IS NULL THEN prest.NM_PRESTADOR ELSE prest.DS_OBS END AS EMPRESA,
      COUNT(CASE WHEN atd.CD_TIP_MAR <> 2 OR atd.CD_TIP_MAR IS NULL THEN 1 ELSE NULL END) AS QTD_CONSULTAS_ATD,
      COUNT(CASE WHEN atd.CD_TIP_MAR = 2 THEN 1 ELSE NULL END) AS QTD_CONSULTAS_RETORNO,
           --
      (COUNT(CASE WHEN atd.CD_TIP_MAR <> 2 OR atd.CD_TIP_MAR IS NULL THEN 1 ELSE NULL END) -
       COUNT(CASE WHEN atd.CD_TIP_MAR = 2 THEN 1 ELSE NULL END)) AS QTD_CONSULTAS_TOTAL
FROM dbamv.PRESTADOR prest
INNER JOIN dbamv.ATENDIME atd
   ON atd.CD_PRESTADOR = prest.CD_PRESTADOR
INNER JOIN dbamv.ESPECIALID espec
   ON espec.CD_ESPECIALID = atd.CD_ESPECIALID
WHERE prest.CD_TIP_PRESTA = 8
AND atd.CD_CONVENIO = 114
AND atd.TP_ATENDIMENTO = 'A'
AND EXTRACT(YEAR FROM atd.DT_ATENDIMENTO) >= 2022 -- tras atendimentos somente apos ano 22
AND EXTRACT(MONTH FROM atd.DT_ATENDIMENTO) >= 06 --trás atendimentos somente após mes 06
AND TO_DATE(TO_CHAR(atd.DT_ATENDIMENTO,'DD/MM/YYYY'),'DD/MM/YYYY')BETWEEN  '01/11/2022' AND '20/11/2022'
GROUP BY
TO_DATE(TO_CHAR(atd.DT_ATENDIMENTO,'DD/MM/YYYY'),'DD/MM/YYYY'),
prest.DS_OBS,
prest.CD_PRESTADOR_REPASSE, prest.CD_PRESTADOR, prest.NM_PRESTADOR,
espec.DS_ESPECIALID, atd.CD_ORI_ATE) res
--WHERE res.CD_PRESTADOR = 7073
--WHERE (TRIM('{AUX_ORIGEM}') IS NULL OR res.CD_ORI_ATE IN ({AUX_ORIGEM}))
GROUP BY res.NM_PRESTADOR, res.CD_PRESTADOR_REPASSE, res.DS_ESPECIALID, res.EMPRESA, res.CD_PRESTADOR, res.PERIODO
