CREATE OR REPLACE VIEW portal_projetos.VW_SOLICITACOES_USUARIO AS


SELECT 
1 AS ORDEM, 
'<i class="fas fa-paper-plane"></i>' AS ICONE,
'Solicitado' AS TIPO,
so.CD_OS, so.DT_PEDIDO, so.DS_SERVICO, so.TP_SITUACAO, 
so.NM_USUARIO AS CD_USUARIO_SOL, usu.NM_USUARIO AS NM_USUARIO_SOL,
so.CD_USUARIO_RECEBE_SOL_SERV AS CD_USUARIO_RESP, usu_resp.NM_USUARIO AS NM_USUARIO_RESP
FROM dbamv.SOLICITACAO_OS so
LEFT JOIN dbasgu.USUARIOS usu
  ON usu.CD_USUARIO = so.NM_USUARIO
LEFT JOIN dbasgu.USUARIOS usu_resp
  ON usu_resp.CD_USUARIO = so.CD_USUARIO_RECEBE_SOL_SERV
WHERE so.TP_SITUACAO IN ('S','A') --ABERTAS
AND so.CD_OFICINA = 28
AND so.CD_USUARIO_RECEBE_SOL_SERV IS NULL --NAO RECEBIDAS
--AND so.NM_USUARIO = 'HSSAMPAIO' -- USUARIO LOGADO

UNION ALL

SELECT 
2 AS ORDEM, 
'<i class="fas fa-user-check"></i>' AS ICONE,
'Recebido' AS TIPO,
so.CD_OS, so.DT_PEDIDO, so.DS_SERVICO, so.TP_SITUACAO, 
so.NM_USUARIO AS CD_USUARIO_SOL, usu.NM_USUARIO AS NM_USUARIO_SOL,
so.CD_USUARIO_RECEBE_SOL_SERV AS CD_USUARIO_RESP, usu_resp.NM_USUARIO AS NM_USUARIO_RESP
FROM dbamv.SOLICITACAO_OS so
LEFT JOIN dbasgu.USUARIOS usu
  ON usu.CD_USUARIO = so.NM_USUARIO
LEFT JOIN dbasgu.USUARIOS usu_resp
  ON usu_resp.CD_USUARIO = so.CD_USUARIO_RECEBE_SOL_SERV
WHERE so.TP_SITUACAO IN ('S','A') --ABERTAS
AND so.CD_OFICINA = 28
AND so.CD_USUARIO_RECEBE_SOL_SERV IS NOT NULL --RECEBIDAS
--AND so.NM_USUARIO = 'HSSAMPAIO' -- USUARIO LOGADO
